### ISSUE TITLE
Error when using CLP as SCIP's linear solver

### ISSUE THREAD

**Issue by hoangtungdinh** [SCIP-Interfaces/JSCIPOpt#6]
Hi,

I'm using your java interface and if I use SoPlex as Scip's linear solver, it works great!

However, when I used CLP as Scip's linear solver, I get the following error when I run the examples. `java -cp scip.jar:examples.jar Linear`

```
java: symbol lookup error: /home/tung/JSCIPOpt/lib/libscipopt.so: undefined symbol: _ZN10ClpSimplexC1Eb
```

I installed Scip using the following script:
```
make LPS=clp LPSOPT=opt ZIMPL=false OPT=opt GMP=false ZLIB=false READLINE=false ZIMPL=false SHARED=true scipoptlib
```

I tested Scip's installation with CLP (using scip's binary). Scip realized that the installed linear solver is CLP and it can solve an example problem. So I think the problem is from the Java interface side.

Would it be possible to use CLP with this java interface?

Thanks!
Tung

**Comment by mueldgog** [comment]
Dear Tung,

nice to hear that you could have used successfully JSCIPOpt with SoPlex.

As far as I can see it, the issue is caused by SCIP's makefile system. Checking the dependencies of libscipopt.so with `ldd` shows that the library does not link to the shared libraries of CLP, which means that libscipopt.so is not complete. In contrast to this, the binary contains the necessary dependencies and thus the binary works well.

This bug needs to be fixed in SCIP, but you can use for now a workaround like this:

Please add `-L/ADDPATH/coin-Clp/lib -lClpSolver -lClp -lCoinUtils -Wl,-rpath,/ADDPATH/coin-Clp/lib` to the last command that is executed when you generate the libscipopt.so. Replace the ADDPATH properly and execute the command in the main directory of your scipoptsuite. Afterwards, you can check the library with `ldd lib/libscipopt.so`, which should now look like

```
>> ldd lib/libscipopt.so 
	linux-vdso.so.1 =>  (0x00007ffeb91a8000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffbdb248000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007ffbdafc8000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007ffbdad81000)
	libClp.so.0 => /home/benny/projects/coin-Clp/lib/libClp.so.0 (0x00007ffbda9cd000)
	libCoinUtils.so.0 => /home/benny/projects/coin-Clp/lib/libCoinUtils.so.0 (0x00007ffbda68c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffbda303000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffbd9ffa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffbd9de3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffbd9a19000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007ffbd97f0000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007ffbd900c000)
	/lib64/ld-linux-x86-64.so.2 (0x00005577cda48000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007ffbd8dcd000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007ffbd882f000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007ffbd84fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffbd82e0000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007ffbd80a0000)
```

With this, the JSCIPOpt should work fine. Alternatively, you could link to CLP explicitly in the CMake of JSCIPOpt (when creating the libjscip.so).

I hope this helps.

Cheers,
Benny

**Comment by mueldgog** [comment]
Okay, please forget everything above. Please change in the Makefile.doit in the main directory of the scipoptsuite the target

`
.PHONY: scipoptlib
scipoptlib:
		$(LIBBUILD) $(LIBBUILDFLAGS) $(LIBBUILD_o)$(SCIPOPTLIBFILE) \
		$(SCIPOPTOBJFILES) $(EXT_LIBS)
`

to

`
.PHONY: scipoptlib
scipoptlib:
		$(LIBBUILD) $(LIBBUILDFLAGS) $(LIBBUILD_o)$(SCIPOPTLIBFILE) \
		$(SCIPOPTOBJFILES) $(EXT_LIBS) $(LPSLDFLAGS)
`

So, just adding the `$(LPSLDFLAGS)`. This fixes the issue.

**Comment by hoangtungdinh** [comment]
Thank you very much Benny. I confirm that adding `$(LPSLDFLAGS)` fixes the issue (and link CLP explicitly in JSCIPOpt cmake works as well).

By the way, I would like to ask whether it is possible to change the Makefile.doit so that the generated `libscipopt.so` has libstdc++ statically linked, that is, adding the option `-static-libstdc++` somehow.

**Comment by hoangtungdinh** [comment]
I execute `-static-libstdc++` using the same approach you mentioned in your first reply (add it to the end of the last executed command) and it works.

Thanks again for your help.

**Comment by mueldgog** [comment]
Sorry for the late reply, I was on parental leave.

Alternatively, you could link statically to the standard libraries when creating the libjscip.so. This would also just require one change, but now in the CMake file of JSCIPOpt.
